#!/usr/bin/python3 -W ignore::DeprecationWarning
# -*- coding:utf8 -*-
import sys
# import spacy
# import stanza
# import torch
# import transformers
import re
import codecs


if __name__ == "__main__":
    input_file = sys.argv[1]
    question_file = sys.argv[2]

    with open(question_file, 'r') as f:
        questions = f.read().split('\n')

    with open(input_file, 'r') as f:
        sentences = f.read().split('\n')

    i = 0
    q = 0
    while q < len(questions):
        tokens = sentences[i].split(' ')
        if len(max(tokens, key=len).strip(',.')) < 1:
            i += 1
            continue
        q += 1
        i += 1
        print(max(tokens, key=len).strip(',.'))